### ISSUE TITLE
As a user I want to decide if the right mouse click cancels the action to add a line/triangle/quad or not.

### ISSUE THREAD

**Issue by fredrikhareide** [nilsschmidt1337/ldparteditor#1034]
**Drawing tri or quad cancelled on pan**
When drawing a tri or quad the action is cancelled if you pan. Sometimes it's needed to pan mid action because of the size of the model

**To Reproduce**
1. Start drawing a tri or quad
2. Pan with left click
3. Watch the action being cancelled

**Comment by nilsschmidt1337** [comment]
@fredrikhareide , hold **Ctrl** during pan and the action is not cancelled.
Cancellation via mouse button was intentional, but maybe I will change the default behaviour in a future release.

**Comment by nilsschmidt1337** [comment]
@fredrikhareide, this "bug" is fxed in the next release. Closed with commit [e38f3b2](https://github.com/nilsschmidt1337/ldparteditor/commit/e38f3b248c1fb5e32a0f3d0aa05242f35c3ddcaa).
