### ISSUE TITLE
Text line selection in the text editor (by clicking on the line numbers) results in wrong inlining when the next line is a reference (type 1).

### ISSUE THREAD

**Issue by fredrikhareide** [nilsschmidt1337/ldparteditor#1036]
**Issues with cursor**
If I press the number in front of a line it selects that line but moves the cursor to the next line. This results in wrong inlining as both lines will be inlined even though only one was selected.

**To Reproduce**
1. Select line via the number in front of the line
2. Click inline
3. You should now see double inlining

**Screenshots**
![image](https://github.com/nilsschmidt1337/ldparteditor/assets/138597179/1a58c41c-2ea3-488d-9078-81e0cb0b5838)

**Comment by nilsschmidt1337** [comment]
Closed with commit [c87055f](https://github.com/nilsschmidt1337/ldparteditor/commit/c87055f5b2242492836ab8707a8561d5b61d3b83).
