### ISSUE TITLE
As a user I want to have a 3D grid follow the rotation.

### ISSUE THREAD

**Issue by fredrikhareide** [nilsschmidt1337/ldparteditor#1037]
Currently the grid behind the part is static also in perspective mode. I want the grid to follow pan, zoom and rotation. More like in other DCCs.

**Comment by nilsschmidt1337** [comment]
Instead of rotating the current grid in perspective mode, I will provide another grid drawn in world space which follows pan, zoom and rotation.

**Comment by nilsschmidt1337** [comment]
Closed with commit [b0eb738](https://github.com/nilsschmidt1337/ldparteditor/commit/b0eb738b9d861a8c90724a622489fff98ac69854).

@fhareide, now you got a new 3D grid (Ctrl+Shift+G), which also rotates, follows pan and zoom.

![Screenshot 2024-06-21 230043](https://github.com/nilsschmidt1337/ldparteditor/assets/11047164/c5c7efb1-e9a7-4e05-bd1e-384551dbbfee)
