### ISSUE TITLE
As a user I want to ctrl-click a subpart or prim in the text editor to open it in the 3D editor and jump straight to it.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1038]
I would like the ability to ctrl click on a line 1 reference (the name part) to open the referenced part and jump to it in LDPE. This is like the functionality to jump to definition of a function or variable in texteditors. I was thinking that when you hold ctrl and hover over it it becomes a link so it's obvious that it's clickable. What do you think? Is it doable?

**Comment by nilsschmidt1337** [comment]
That's doable. I would add a tooltip, too. It will show that you can follow the reference with ctrl-click.
Instead of showing the underline when you hover over the filename, I would prefer to show it already when the user presses ctrl.

**Comment by nilsschmidt1337** [comment]
Closed with commit [88a9565](https://github.com/nilsschmidt1337/ldparteditor/commit/88a956584069eb1803286615e0edd644849159fa).
@fhareide , I added a tooltip on all text- and 3D-editor tab headers to show the location of the newly opened file, too.
