### ISSUE TITLE
Join Selection (Text Editor) had problems when INVERTNEXT was on top of the selection.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1045]
This really is a corner case but if you have the following situation

![image](https://github.com/nilsschmidt1337/ldparteditor/assets/12023679/eb0e3d96-94b0-4ebc-92da-6b18ce60fbb4)

And you try to "Join Selection" on the top and bottom primitives you get an issue where the INVERTNEXT from the other primitive gets put in the wrong position like this

![image](https://github.com/nilsschmidt1337/ldparteditor/assets/12023679/889904fb-c082-4055-b011-72c342851f7b)

**Comment by nilsschmidt1337** [comment]
Closed with commit [b2f9c9b](https://github.com/nilsschmidt1337/ldparteditor/commit/b2f9c9bcf2ebf3008dec122771208d998c29553e).
