### ISSUE TITLE
As a user I want to do simple math in the text editor.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1047]
Would it be possible to be able to do e.g. 3.35+4.1 and make it evaluate straight in the editor. Would be nice for moving primitives and so on.

**Comment by nilsschmidt1337** [comment]
@fhareide, this is already possible, but limited to the !LPE CONST meta command.
```
0 !LPE CONST a = 3.35+4.1
2 24 0 0 0 a 0 -a
```

You can inline the constant and do re-calculations with the ["Update/Compile linked Subfile Data"](https://raw.githubusercontent.com/nilsschmidt1337/ldparteditor/master/icons/svg/subcompile.svg) button.

**Comment by fhareide** [comment]
Not quite what I had in mind as this will take me more time than opening the calculator. My wish is that + and - is "triggers" to after for example hitting enter it will calculate inline.

**Comment by nilsschmidt1337** [comment]
Ok, now I got it. The line contains some math. Hitting enter at the end of the line would trigger the calculation in the text editor for only this line.

**Comment by fhareide** [comment]
Yep! That's correct. Like a lot of other programs do. That would be handy in other input fields too. Like set XYZ position and such.

**Comment by nilsschmidt1337** [comment]
Closed with commit [e55bc65](https://github.com/nilsschmidt1337/ldparteditor/commit/e55bc65c0727668b883aed16df1f0908e66af524).

**Comment by nilsschmidt1337** [comment]
_F. Hareide wrote:_

> Could you also fix it to jump to the end of evaluated in texteditor? That is where I use the math functions the most actually. I never do more than one at a time. but I guess if people do more than one maybe set to the end of the last one?

Actually, I will "jump" to the end of the current group, regardless if there was a calculation in this group or not.

_Example 1:_
`2 24 0 0 0 1+|1 0 2+3`
`2 24 0 0 0 2| 0 5`

_Example 2:_
`2 24 0 0 0| 1+1 0 2+3`
`2 24 0 0 0| 2 0 5`

_Example 3:_
`2 24 0 0 0 1+1 0 |2+3`
`2 24 0 0 0 2 0 5|`

_Example 4:_
`2 2|4 0 0 0 1+1 0 2+3`
`2 24| 0 0 0 2 0 5`

_Example 5:_
` |2 24 0 0 0 1+1 0 2+3`
`2| 24 0 0 0 2 0 5`

**Comment by fhareide** [comment]
Makes sense to me 👍

**Comment by nilsschmidt1337** [comment]
Closed with commit [41ead3f](https://github.com/nilsschmidt1337/ldparteditor/commit/41ead3f538d862b647b837a2fee341d67511c2a1).
