### ISSUE TITLE
As a user I want to calibrate a background image with a measurement.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1048]
When placing an image for reference it would be superhandy to have a button called calibrate that let you perform a measurement on the image and input a value you want that measurement to be. Some math would then be applied to scale the image to make that measurement be correct. 

![image](https://github.com/nilsschmidt1337/ldparteditor/assets/12023679/9995c4d2-310a-4232-a46c-251381d5bdff)

So on the image I did a measurement and when I finish the measurement I get an input box with the logical length and I for example for this case input 27.7 LDU and the image would calibrate. Doable?

**Comment by nilsschmidt1337** [comment]
Required calculations:
- [ ] Calculate a scaling factor (factor = newLength / oldLength) , old- and newLength not equal zero!
- [ ] Project the line starting point to the background image "2D" coordinate system (point P1).
- [ ] Calculate the difference (D1) between the background image "2D" center (C1) and P1.
- [ ] Translate the background image by ((D1 - D1 * factor) / 2.0).
- [ ] Scale the image width and height by the factor.

**Comment by nilsschmidt1337** [comment]
Closed with commit [e3c2a4b](https://github.com/nilsschmidt1337/ldparteditor/commit/e3c2a4b4791a60a7f25df2dc0190b6af0ec06b02).

@fhareide, you can now click on the "Calibrate Backround Image Button" and select a line (type 2, 5 or distance) in the 3D view and move the mouse a little bit. Then a dialog will pop up to input the logical length in any unit you want (mm, ldu, stud, inch).
The image will be scaled and translated accordingly.

![Screenshot 2024-06-27 225350](https://github.com/nilsschmidt1337/ldparteditor/assets/11047164/66e4cf2b-0f5b-4b99-a395-91fe99b53e1d)
