### ISSUE TITLE
As a user I want to do simple math in floating point number input fields.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#1049]

**Comment by nilsschmidt1337** [comment]
Closed with commit [94fab89](https://github.com/nilsschmidt1337/ldparteditor/commit/94fab89a116e2eaa8fa2b53bec5ee232a0834704).

**Comment by fhareide** [comment]
This feature is AMAZING! I use it all the time! Do you think it would be able to put the cursor at the end of the last solved value? That way you can quickly do more operations directly on the solved value without moving the cursor first.

**Comment by nilsschmidt1337** [comment]
Done. Was a one-liner.

**Comment by fhareide** [comment]
Thanks! I have noticed that this feature is very slow the first time after restart. Is that something that can be fixed?

**Comment by fhareide** [comment]
Could you also fix it in the jump to end of evaluated in texteditor? That is where I use the math functions the most actually. I never do more than one at a time. but I guess if people do more than one maybe set to the end of the last one?

**Comment by nilsschmidt1337** [comment]
Closed with commit [5268b1a](https://github.com/nilsschmidt1337/ldparteditor/commit/5268b1a0477c0a21049a508d1edb57d1ebfb4062). It should be faster now. A fix to jump to the end of evaluated in texteditor is planned.
