### ISSUE TITLE
As a user I want a faster way to move, rotate and scale. 

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1050]
It would be really nice to have a faster way to move/rotate/scale. I want it to default to world.

My idea is to make something similar to how Blender does it with the G, S and R keys.

To move you press G once. Then after it's triggered you can press X, Y or Z to lock to an axis. Or Ctrl-shift-x and so on to lock to a plane. Also while this is active you can input a number on how far you want to move relative. As long as this is active the thing you are moving sticks to the cursor. You should probably try the G command in Blender before deciding.

But in my opinion this would be very helpful and increase my efficiency

**Comment by nilsschmidt1337** [comment]
This is a really cool request! I will implement it when this is done:

- [ ] #1058

**Comment by nilsschmidt1337** [comment]
Closed with commit [98007dc](https://github.com/nilsschmidt1337/ldparteditor/commit/98007dc072c85c6ed2842c364f1bf1dfd354b569).
