### ISSUE TITLE
As a user I want to be able to "un-inline".

### ISSUE THREAD

**Issue by fredrikhareide** [nilsschmidt1337/ldparteditor#1052]
Inlining is great. Especially the linked one. But it would be really nice if it was possible to un-inline. So basically get back to having the referenced part again. And for linked it might be smart to ask to update first maybe. Is that possible?

**Comment by nilsschmidt1337** [comment]
I though about it before. This is difficult, since it deletes(replaces) contents in the linked destination and in the current file in one go. I simply don't want to do that.

**Comment by nilsschmidt1337** [comment]
Closed with commit [8d7f137](https://github.com/nilsschmidt1337/ldparteditor/commit/8d7f1372bf76f58341568b85891b426707c20072).

**Comment by nilsschmidt1337** [comment]
An edge case for path separators (slashes) in the subfile name needs to be fixed.
