### ISSUE TITLE
Undoing at the end of the file leads to wrong line number.

### ISSUE THREAD

**Issue by fredrikhareide** [nilsschmidt1337/ldparteditor#1054]
![image](https://github.com/nilsschmidt1337/ldparteditor/assets/138597179/bb5fcd97-fac9-428c-ba56-113253bc800b)

Sometimes when I undo stuff at the end of the file the linenumbers gets messed up. The next line is selected when I hit the line I want to select. It usually corrects itself after scrolling

(after scrolling)
![image](https://github.com/nilsschmidt1337/ldparteditor/assets/138597179/dfeaaa16-70a0-4d22-8882-703ccf158f5c)

https://github.com/nilsschmidt1337/ldparteditor/assets/11047164/c4cf1097-bac1-4785-bbce-16602b8bc3f5

**Comment by nilsschmidt1337** [comment]
Closed with commit [48371b1](https://github.com/nilsschmidt1337/ldparteditor/commit/48371b1e3b51a597112b169c293bcb006b588f41).

**Comment by nilsschmidt1337** [comment]
@fredrikhareide , was this problem solved now?

**Comment by fhareide** [comment]
Unfortunately it does seem to still happen

**Comment by nilsschmidt1337** [comment]
@fhareide , how can I reproduce the problem? I tried undo at the end of the file, but everything works as expected.

**Comment by fhareide** [comment]
Paste this into a new file. Scroll all the way down. And then with the cursor over the 3d view try to undo. Seems to happen even more now. Might be another bug maybe

`1 16 -14.5 -4.25 0 -6 0 0 0 0 -6 0 -12 0 1-4cylo.dat
1 16 -14.5 -4.25 -12 -6 0 0 0 0 -6 0 1 0 1-4chrd.dat
1 16 -13.21 3.81 0 0 0 -6 6 0 0 0 -12 0 3-16cylo.dat
1 16 -13.21 3.81 -12 0 0 -6 6 0 0 0 1 0 3-16chrd.dat
1 16 19.6267 .9281 -6 -.8733 0 0 5.1781 -1 0 0 0 6 rect2p.dat
1 16 -19.6267 .9281 -6 -.8733 0 0 -5.1781 -1 0 0 0 6 rect2p.dat
1 16 0 9.81 -6 13.21 0 0 0 -1 0 0 0 -6 rect2p.dat
1 16 0 -10.25 -6 14.5 0 0 0 1 0 0 0 6 rect2p.dat
4 16 -8.9 -3.74 -12 -8.9 -5.74 -12 -11.9 -5.74 -12 -11.9 -3.74 -12
4 16 -8.9 -1.74 -12 -8.9 -3.74 -12 -11.9 -3.74 -12 -11.9 -1.74 -12
4 16 -2 -3.74 -12 -2 -5.74 -12 -4.9 -5.74 -12 -4.9 -3.74 -12
4 16 -2 -3.74 -12 -4.9 -3.74 -12 -4.9 -1.74 -12 -2 -1.74 -12
4 16 4.9 -3.74 -12 4.9 -5.74 -12 2 -5.74 -12 2 -3.74 -12
4 16 4.9 -1.74 -12 4.9 -3.74 -12 2 -3.74 -12 2 -1.74 -12
4 16 11.9 -3.74 -12 11.9 -5.74 -12 8.9 -5.74 -12 8.9 -3.74 -12
4 16 11.9 -1.74 -12 11.9 -3.74 -12 8.9 -3.74 -12 8.9 -1.74 -12
4 16 5.5 1.3 -12 8.4 1.3 -12 8.9 -1.74 -12 6.9 -1.74 -12
4 16 11.9 -1.74 -12 8.9 -1.74 -12 8.4 1.3 -12 10.4 1.3 -12
4 16 10.4 1.3 -12 12.4 1.3 -12 13.9 -1.74 -12 11.9 -1.74 -12
4 16 -5.5 3.3 -12 -5.5 1.3 -12 -8.4 1.3 -12 -8.4 3.3 -12
4 16 -5.5 1.3 -12 -6.9 -1.74 -12 -8.9 -1.74 -12 -8.4 1.3 -12
4 16 -3.5 1.3 -12 -4.9 -1.74 -12 -6.9 -1.74 -12 -5.5 1.3 -12
4 16 -11.9 -1.74 -12 -10.4 1.3 -12 -8.4 1.3 -12 -8.9 -1.74 -12
4 16 -13.9 -1.74 -12 -12.4 1.3 -12 -10.4 1.3 -12 -11.9 -1.74 -12
4 16 -4.9 -1.74 -12 -3.5 1.3 -12 -1.5 1.3 -12 -2 -1.74 -12
4 16 1.5 1.3 -12 0 -1.74 -12 -2 -1.74 -12 -1.5 1.3 -12
3 16 0 -1.74 -12 1.5 1.3 -12 2 -1.74 -12
4 16 4.9 -1.74 -12 2 -1.74 -12 1.5 1.3 -12 3.5 1.3 -12
4 16 6.9 -1.74 -12 4.9 -1.74 -12 3.5 1.3 -12 5.5 1.3 -12
4 16 12.4 1.3 -12 18.7534 6.1062 -12 15.9 -1.74 -12 13.9 -1.74 -12
4 16 -12.4 1.3 -12 -13.9 -1.74 -12 -15.9 -1.74 -12 -18.7534 6.1062 -12
3 16 -12.4 3.3 -12 -12.4 1.3 -12 -18.7534 6.1062 -12
4 16 -12.4 3.3 -12 -18.7534 6.1062 -12 -13.21 9.81 -12 -12.4 5.3 -12
4 16 -18.7534 6.1062 -12 -15.9 -1.74 -12 -15.9 -3.74 -12 -20.5 -4.25 -12
3 16 -15.9 -3.74 -12 -15.9 -5.74 -12 -20.5 -4.25 -12
3 16 -15.9 -5.74 -12 -14.5 -10.25 -12 -20.5 -4.25 -12
3 16 -13.9 -5.74 -12 -14.5 -10.25 -12 -15.9 -5.74 -12
3 16 -13.9 -5.74 -12 -11.9 -5.74 -12 -14.5 -10.25 -12
3 16 -14.5 -10.25 -12 -11.9 -5.74 -12 -8.9 -5.74 -12
3 16 -14.5 -10.25 -12 -8.9 -5.74 -12 -6.9 -5.74 -12
3 16 -14.5 -10.25 -12 -6.9 -5.74 -12 -4.9 -5.74 -12
3 16 13.9 -5.74 -12 15.9 -5.74 -12 14.5 -10.25 -12
3 16 11.9 -5.74 -12 13.9 -5.74 -12 14.5 -10.25 -12
3 16 20.5 -4.25 -12 14.5 -10.25 -12 15.9 -5.74 -12
3 16 15.9 -5.74 -12 15.9 -3.74 -12 20.5 -4.25 -12
4 16 15.9 -3.74 -12 15.9 -1.74 -12 18.7534 6.1062 -12 20.5 -4.25 -12
3 16 8.9 -5.74 -12 11.9 -5.74 -12 14.5 -10.25 -12
3 16 6.9 -5.74 -12 8.9 -5.74 -12 14.5 -10.25 -12
3 16 4.9 -5.74 -12 6.9 -5.74 -12 14.5 -10.25 -12
3 16 2 -5.74 -12 4.9 -5.74 -12 14.5 -10.25 -12
4 16 -14.5 -10.25 -12 0 -5.74 -12 2 -5.74 -12 14.5 -10.25 -12
3 16 -4.9 -5.74 -12 -2 -5.74 -12 -14.5 -10.25 -12
3 16 -2 -5.74 -12 0 -5.74 -12 -14.5 -10.25 -12
4 16 1.5 1.3 -12 -1.5 1.3 -12 -1.5 3.3 -12 1.5 3.3 -12
4 16 -1.5 5.3 -12 1.5 5.3 -12 1.5 3.3 -12 -1.5 3.3 -12
4 16 -5.5 3.3 -12 -8.4 3.3 -12 -8.4 5.3 -12 -5.5 5.3 -12
4 16 8.4 3.3 -12 8.4 1.3 -12 5.5 1.3 -12 5.5 3.3 -12
4 16 8.4 5.3 -12 8.4 3.3 -12 5.5 3.3 -12 5.5 5.3 -12
3 16 18.7534 6.1062 -12 12.4 1.3 -12 12.4 3.3 -12
4 16 13.21 9.81 -12 18.7534 6.1062 -12 12.4 3.3 -12 12.4 5.3 -12
3 16 -13.21 9.81 -12 -10.4 5.3 -12 -12.4 5.3 -12
3 16 -13.21 9.81 -12 -8.4 5.3 -12 -10.4 5.3 -12
3 16 -13.21 9.81 -12 -5.5 5.3 -12 -8.4 5.3 -12
3 16 12.4 5.3 -12 10.4 5.3 -12 13.21 9.81 -12
3 16 10.4 5.3 -12 8.4 5.3 -12 13.21 9.81 -12
3 16 8.4 5.3 -12 5.5 5.3 -12 13.21 9.81 -12
3 16 5.5 5.3 -12 3.5 5.3 -12 13.21 9.81 -12
3 16 3.5 5.3 -12 1.5 5.3 -12 13.21 9.81 -12
4 16 13.21 9.81 -12 1.5 5.3 -12 -1.5 5.3 -12 -13.21 9.81 -12`

**Comment by nilsschmidt1337** [comment]
@fhareide , thanks. Would it be possible to get a screen recording of this bug, too?
I was not able to reproduce the issue, yet.

**Comment by fhareide** [comment]
Absolutely, here you go. It seems to happen a lot now. I am running 1.8.80 from source. 3840x2160 resolution. Windows 11
https://www.dropbox.com/scl/fi/41jy95j4s13dpwfhwkyxm/2024-06-18-09-02-52.mp4?rlkey=f9vxoz4a02aokcfztmjxtavyd&dl=0

**Comment by nilsschmidt1337** [comment]
I was able to reproduce it:

1. 4K screen, 200% scale, Win 11
2. Open the program
3. Paste the content above into new.dat, resulting in 77 lines
4. Modify the last line by appending a space
5. Focus on the 3D view
6. Click the undo button in the 3D editor with the mouse

**Comment by fhareide** [comment]
Nice work! I have 100% scale but glad you found a way to reproduce. Then it might be easier to find a fix too :)

**Comment by nilsschmidt1337** [comment]
Closed with commit [cf39e96](https://github.com/nilsschmidt1337/ldparteditor/commit/cf39e9666c16c054b780e609a0ce03b35f57f434).
Thanks, @fhareide . Finally, I was able to fix it.
