### ISSUE TITLE
As a user I want to be able to export a file with its references into a zip file.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1057]
Do you think it would be possible to add a collect file option in LDPE where you can take all files needed by the current file and make a zip file with the correct folder structure. I'm thinking only if the files are not referenced from offical or unofficial library.  This would be superhandy.

**Comment by nilsschmidt1337** [comment]
Closed with commit [26b35eb](https://github.com/nilsschmidt1337/ldparteditor/commit/26b35ebf22c5c6ee9115d44e5cb74e603efc3e3b).
