### ISSUE TITLE
As a user I want an upgraded gizmo/manipulator.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1058]
![image](https://github.com/nilsschmidt1337/ldparteditor/assets/12023679/27a4e74d-4c34-4094-b8bb-fe4f05e3504a)

We are currently lacking scaling and moving locked to a plane. I propose that we change the gizmo to look like this and give the squares inbetween the ability to scale and translate on a plane. This has become a standard and would be a great addition. What do you think?

**Comment by nilsschmidt1337** [comment]
Closed with commit [e59a521](https://github.com/nilsschmidt1337/ldparteditor/commit/e59a521d0116f2d79e3c044ccf13a4edcb014422).
