### ISSUE TITLE
As a user I want a different selection color than red in backface-culling modes.

### ISSUE THREAD

**Issue by fhareide** [nilsschmidt1337/ldparteditor#1087]
When selecting a mode with red back faces it would be nice to have a different selection color

**Comment by nilsschmidt1337** [comment]
@fhareide, closed with commit [9b4cfa0](https://github.com/nilsschmidt1337/ldparteditor/commit/9b4cfa01ce8c8fb09bf17fe7134dfc0e7617801f).
