### ISSUE TITLE
Can't get past the configuration screen

### ISSUE THREAD

**Issue by ali1234** [nilsschmidt1337/ldparteditor#705]
![screenshot_2018-10-30_20-34-32](https://user-images.githubusercontent.com/651970/47748713-5d5cf600-dc83-11e8-9af9-2ba6d2396f40.png)

I have filled in all the fields to the best of my ability, but still the "OK" button is disabled and I can't get into the actual program. I tried putting in a fake LDraw username (because I don't have one) but this did not help either. There is no indication of what is missing.

**Comment by nilsschmidt1337** [comment]
Hi Alistair,

are the read and write permissions for your folders correct?

Cheers,
Nils

**Comment by ali1234** [comment]
They are both world-readable.

**Comment by nilsschmidt1337** [comment]
That explains it. The application needs write access to /usr/share/ldraw/Unofficial.
You can change the folder to a new one (e.g. in your home directory /home/al/Source/ldrawstuff/Unofficial and it should work)

I will include a warning message in a future release. Thanks!

**Comment by nilsschmidt1337** [comment]
I implemented #708 and it will be included in the next 0.8.46 release.
With the new release you will see some hints on the configuration screen if something is missing.
