### ISSUE TITLE
Try to use modern OpenGL if the context for legacy OpenGL can't be created (was: LDPartEditor not starting)

### ISSUE THREAD

**Issue by tcuje** [nilsschmidt1337/ldparteditor#711]
Output from **glxinfo**:
[glxinfo](https://github.com/nilsschmidt1337/ldparteditor/files/3090924/glxinfo.txt)

I get the following error in error_log.txt
```[ERROR 0.8.45] @org.nschmidt.ldparteditor.splash.SplashScreen
java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:344)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:296)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:163)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)```

Also on Console I see:
```(SWT:24887): Gdk-ERROR **: 21:53:11.825: The program 'SWT' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 521 error_code 8 request_code 154 (GLX) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
./run.sh: Zeile 1: 24887 Trace/Breakpoint ausgelöst   (Speicherabzug geschrieben) java -Djava.library.path='natives/' -jar LDPartEditor.jar
```

Im using Linux Mint 19 and tried with Java 1.8 and Java 11 Runtime.

**Comment by nilsschmidt1337** [comment]
Hi @tcuje ,

please try to run **glxgears** on your machine to see if you 3D acceleration is working correcly.
It would be interesting what **glxinfo** will tell you, too. Both programs are included in the _mesa-utils_ package.
[https://community.linuxmint.com/software/view/mesa-utils](https://community.linuxmint.com/software/view/mesa-utils)

Cheers,
Nils

**Comment by tcuje** [comment]
Hi, thanks for the fast reply! glxgears works nicely.

glxinfo says: https://pastebin.com/vk3F5Kdk

**Comment by nilsschmidt1337** [comment]
Thanks @tcuje ,

I think I can fix it! Your graphics card and linux version do not support the old legacy OpenGL 2.1 features (with the fixed function pipeline). Unfortunately it is the default (and fallback) option in the LDPartEditor program, since most cards are still compatible with this version. Luckily, I already implemented the support for modern OpenGL 3.3.

What I will do now is to implement the following logic:
```
if (legacy OpenGL is favoured) {
 try to create a context for legacy OpenGL
 if it fails try to create a context for modern OpenGL
} else {
 try to create a context for modern OpenGL
 if it fails try to create a context for legacy OpenGL
}
```

It can take 4-8 weeks until I will publish a new release. I try to be faster, but work and private life require a lot of energy at the moment.

**Comment by nilsschmidt1337** [comment]
Hi @tcuje,

I recently created an alternative linux build which can possibly run Linux Mint 19
https://github.com/nilsschmidt1337/ldparteditor/releases/download/v0.8.46-beta/LDPartEditor_linux_x64_alternative.zip

Cheers,
Nils

**Comment by defransen** [comment]
Hi,
I can confirm that the alternative version is running on my Arch - Gnome 3 - Wayland - Mesa 19.0.6 OpenGL 4.2 machine, it shows "OpenGL 2.0" in the title bar. Guess that is the compatibility profile.
But the 0.8.47 version gives an error: "unsupported color depth" during `org.eclipse.swt.opengl.GLCanvas` initialization, though it's properly catched now ;)
Googling around makes me think that is a well known problem of the GLCanvas class. There seems to be no way to request a specific profile.
Are there any (usable) alternative GL classes for Java?

**Comment by nilsschmidt1337** [comment]
@defransen there is indeed an alternative GLCanvas class for Java.
Please take a look here:  [https://github.com/LWJGLX/lwjgl3-swt](https://github.com/LWJGLX/lwjgl3-swt)
I watch this repository since years but I don't want to switch because there is still no support for OS X.
