### ISSUE TITLE
Make face from 3 or 4 selected vertices?

### ISSUE THREAD

**Issue by chambm** [nilsschmidt1337/ldparteditor#717]
I'm not sure whether this is already possible (couldn't figure it out myself and didn't see it in the tutorial/wiki), but when editing an existing part, I want to use move its vertices around and make a face based on 3 or 4 vertices rather than free drawing it. Just like making a line between 2 selected vertices.

**Comment by nilsschmidt1337** [comment]
Hi @chambm,

just activate "Create a new triangle..." and select the three or four vertices with a selection rectangle.
You have to hold the left² mouse button and drag the mouse over the area of the vertices.
( ² or the right mouse button if you are using a mouse with your left hand.)

![SelectVertices](https://user-images.githubusercontent.com/11047164/59144722-066a8c80-89db-11e9-8efd-85a97d453fd4.PNG)

![AddTriangle](https://user-images.githubusercontent.com/11047164/59144728-12564e80-89db-11e9-87d2-fafb6586214d.PNG)

You can even select the vertices one-by-one with this rectangular selection.
Or two vertices first and then the last one. Or one and then two etc.

Cheers,
Nils
