### ISSUE TITLE
Sub parts not showing up

### ISSUE THREAD

**Issue by mjhorvath** [nilsschmidt1337/ldparteditor#718]
[a608p33.dat](https://github.com/nilsschmidt1337/ldparteditor/files/3438990/a608p33.dat.txt)

The sub part 1-4disc.dat is not showing up in my part. There is just blank space where the sub part should be.

https://drive.google.com/open?id=1JsoVg3Pcd2_1UktHwDv5z09iCpvpvYsL

Version 0.8.46

**Comment by nilsschmidt1337** [comment]
Hi Michael ( @mjhorvath ),

the transformation matrix of each 1-4disc.dat reference is singular. It actually something which needs to be solved by the part author. LDPE provides a feature for this. You can simply "quick fix" these errors by right clicking on the error entry in the text editor and the select "Quick fix similar problems".
It is just a problem in the definition of the part.

Cheers,
Nils

**Comment by mjhorvath** [comment]
Thank you! That did indeed fix my problem.
