### ISSUE TITLE
As a user I want to re-map mouse controls.

### ISSUE THREAD

**Issue by mjhorvath** [nilsschmidt1337/ldparteditor#719]
Is it possible to re-map the mouse controls? I use multiple programs and it is hard to remember the mouse controls are not the same in this one. Thanks.

**Comment by nilsschmidt1337** [comment]
@mjhorvath , sure. Could you please elaborate? It is not clear to me what you want to re-map and how it should behave.

**Comment by mjhorvath** [comment]
Thanks for listening! For instance, I would like to switch the middle mouse button and right mouse button behaviors. I would like to pan the view using the middle mouse button, and rotate the view using the right mouse button. If I could configure these behaviors in settings, it would be great!

**Comment by nilsschmidt1337** [comment]
@mjhorvath , got it. I will see what I can do.

**Comment by nilsschmidt1337** [comment]
@mjhorvath , I was able to implement such a feature. I will publish it with a new release in the next 48 hours.

**Comment by nilsschmidt1337** [comment]
Closed with commit 99374c9.
