### ISSUE TITLE
Display issues on a 3840x2160 display: empty regions & missplaced cursor

### ISSUE THREAD

**Issue by swl2019** [nilsschmidt1337/ldparteditor#723]
Hi
I like the program and think it is providing realy help and Benefit to part designers. 

However, on my computer it has issues displaying the 3d model using the full avialable space - please see attached screen dump. 

The turquise rectangel is not using the avialable space (rest keeps empty) and when I marked the red selection frame my cursor was on the green marked possition (more up and right, outside the red as well as turquise frames)
Also the left panes do not use all avialable space. But the Editor on the right hand is not affected.

 I was not able to find any configuration, but if I missed an option please point me to it.

Thank you
Best Regards 
Jörg

![Capture](https://user-images.githubusercontent.com/48833324/63085813-b960e480-bf4e-11e9-8cdd-79175eeb2edc.PNG)

**Comment by nilsschmidt1337** [comment]
Hi Jörg (@swl2019),

I was able to reproduce this issue on a higher resolution while using DSR.
Thanks for reporting the bug. I will work on this with higher priority.

Cheers,
Nils

**Comment by swl2019** [comment]
Hi Nils,

thank you. If you need any assistance don't hesitate to ask for.

Best Regards
Jörg

**Comment by nilsschmidt1337** [comment]
Hi Jörg (@swl2019),

I was able to add such configuration possibility to the program options.
It will be included in the next 0.8.48 release which will be published next week.

When you open the options menu you will see a "Viewport Scale Factor".
Increase the value from 1.0 to 2.0 and your display issues are gone.

![Options](https://user-images.githubusercontent.com/11047164/63650917-2430cd80-c750-11e9-9cca-cae1679c0b6a.PNG)

![ViewportScaleFactor](https://user-images.githubusercontent.com/11047164/63650923-314dbc80-c750-11e9-903b-9671d2988e58.PNG)

**Comment by nilsschmidt1337** [comment]
Closed with commit 4224953.

**Comment by nilsschmidt1337** [comment]
Hi Jörg ( @swl2019 ),

I just published a new release which includes this feature.

Cheers,
Nils

**Comment by swl2019** [comment]
Hi Nils.

Thank you - it worked as expected. Now it is much easier to navigate (which was in principle possible, but quite nasty in the old version)

Cheers
Jörg
