### ISSUE TITLE
Can't open ldparteditor, Please help!

### ISSUE THREAD

**Issue by JustLearning62** [nilsschmidt1337/ldparteditor#737]
I'm having problem trying to open the program, it actually open a dialog saying that it needs the current java runtime to open, BUT I have already installed the current version of java. What I do? I'm using Windows 10 in the PC.  Please reply at westrichard637@gmail.com.

**Comment by nilsschmidt1337** [comment]
Hi @JustLearning62 , did you install the 64-bit JRE on your PC? It can only run on a 64-bit Java environment.
