### ISSUE TITLE
Cannot run LDPE - (64-bit Java installation missing)

### ISSUE THREAD

**Issue by jwalt2065** [nilsschmidt1337/ldparteditor#746]
I just found out about LDPE and installed it in my win10 computer. I successfully installed the latest version of Java 1.8.241. I get an error when starting LDPE that I need Java 1.8.0 and it directs me to the Java download page.

**Comment by nilsschmidt1337** [comment]
Hi!
- Did you choose to install a 64-bit version of Java? (https://github.com/nilsschmidt1337/ldparteditor/wiki/How-to-check-if-the-Java-Virtual-Machine-is-32-or-64-bit)
- Have you tried to run "java -version" on the command line?
- You can install a higher version of the JDK  (e.g. Java 14)

Cheers,
Nils

**Comment by nilsschmidt1337** [comment]
I was able to reproduce it with the buggy Oracle JDK installer.
@jwalt2065 you have to include the bin folder of the JDK to the PATH environment variable.
The path can be something like "C:\Program Files\Java\jdk1.8.0_241\bin" or "C:\Program Files\Java\jre1.8.0_241\bin".

I installed the JDK-14 on my machine. So it is ""C:\Program Files\Java\jdk-14\bin" for me.

**Comment by jwalt2065** [comment]
Hi Nils,
I didn't have the 64 bit version of Java installed. IT is working now.

I have been corresponding with Philo and he told me about LDPE.
I created Lego 24121 Curved Gear Rack 11X11 and sent it to Philo.
I used L3Lab and Windows Notebook. I drew the part with CorelDraw to get the coordinates and LDCad to rotate a part to get the orientation matrix numbers. I was looking for something better than L3Lab.

Where can I find help to get started using LDPE?

Thanks,
John

**Comment by nilsschmidt1337** [comment]
Hi John (@jwalt2065),

you can find a manual here:
https://translate.google.com/translate?sl=fr&tl=en&u=https%3A%2F%2Fjc-tchang.philohome.com%2Fmanuel%2FLDPartEditor.htm

and a small wiki page here:
https://github.com/nilsschmidt1337/ldparteditor/wiki/Home-Backup

LDPE is powerful, but it is also a little bit complex (its hard to learn, like other CAD programs).

Kind Regards,
Nils

**Comment by jwalt2065** [comment]
Thanks Nils.
Just a quick question, is there the option to put the part viewer on one monitor and the text editor on another?

Regards,
John

**Comment by nilsschmidt1337** [comment]
Click on "Tools..." -> "Options..." and choose "Seperate Windows" for "Text and 3D editor arrangement".
You need to restart the program to get the changes to be applied.

**Comment by nilsschmidt1337** [comment]
With the release of [LDPartEditor 1.8.54-beta](https://github.com/nilsschmidt1337/ldparteditor/releases/tag/v1.8.54-beta) it is no longer necessary to install Java separately.
