### ISSUE TITLE
Meccano/Erector parts creating

### ISSUE THREAD

**Issue by Symbian9** [nilsschmidt1337/ldparteditor#852]
How to setup LDPartEditor for creating *Meccano/Erector* (imperial units) & *Merkur* (metric units) sets parts? (at least for strips & plates)

### REFERENCES

- https://en.wikipedia.org/wiki/Meccano
  - https://meccanoindex.co.uk/Drawings/Parts.php?id=1634405614
  - https://www.usmeccano.com/other/meccstrips.htm
- https://en.wikipedia.org/wiki/Erector_Set
- https://en.wikipedia.org/wiki/Merkur_(toy)

**Comment by nilsschmidt1337** [comment]
@Symbian9 I created a discussion here https://github.com/nilsschmidt1337/ldparteditor/discussions/885
I would like to answer in the next days.

**Comment by Symbian9** [comment]
Thanks!
