### ISSUE TITLE
Calls to setWeights() should not use array creation for varargs parameters.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#866]
e.g. in PrimGen2Design.java at line 308:
`sashForm.setWeights(new int[]{33, 66});  // Noncompliant: unnecessary`
should be
`sashForm.setWeights(33, 66);`

There are 29 references to `.setWeights(new int[]{...});` in the code base (master branch).

![setWeights](https://user-images.githubusercontent.com/11047164/150572981-9897f55b-eee5-4bb0-844e-e332935a884b.png)

**Comment by RishiKumarRay** [comment]
Thanks @nilsschmidt1337 will generate a PR soon

**Comment by nilsschmidt1337** [comment]
Thanks!

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 please review PR #867
